### ISSUE TITLE
Add tutorial on ssh tunneling into vesta through a text editor

### ISSUE THREAD

**Issue by t-davidson** [socdyn/wiki#3]
I heard that George has a nifty way of using Atom text editor locally to tunnel into Vesta. It would be great to have a tutorial on this similar to the one I wrote for Jupyter Notebooks

**Comment by georgeberry** [comment]
Will do!

**Comment by chrisjcameron** [comment]
Is the the route that involves installing and running a JavaScript based server on Vesta? Make sure to do the necessary security research before enabling.

**Comment by georgeberry** [comment]
@chrisjcameron that is the Nuclide sever approach. That is a sort of professional solution, in the sense that it requires everyone to use Atom + Nuclide.

I was going to instead go through remote editing with Atom and Sublime

**Comment by georgeberry** [comment]
Done for Atom + Nuclide
