### ISSUE TITLE
Improve Github tutorial

### ISSUE THREAD

**Issue by t-davidson** [socdyn/wiki#4]
Although there is some info on Github it would be great to flesh this out a bit more including info about best practices.

While Github has great tutorials I think it can be confusing for new users so this resource would ideally help encourage more exploration.

**Comment by georgeberry** [comment]
I'll claim this—I wrote the existing tutorial

**Comment by georgeberry** [comment]
[this file](https://github.com/socdyn/wiki/blob/master/git.md) now contains a better git tutorial that explains basic features
